spring:
 application:
  name: SpringBootProject-6_Crud_DataJPA
#jdbc properties(Oracle)
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql:///springboot_practice 
  username: root
  password: Hasnat@2516

 jpa:
  #database-platform: org.hibernate.dialect.MySQLDialect
  show-sql: true
  hibernate:
   ddl-auto: update
        
